"""Portal API key verification for self-hosted deployments.

Used when odoo-mcp-pro runs alongside odoo-mcp-portal without Zitadel.
The Bearer token IS the raw MCP API key generated by the portal.

Flow:
  1. MCP client sends  Authorization: Bearer <raw_api_key>
  2. PortalKeyVerifier.verify_token(raw_key) hashes it → key_hash
  3. Queries mcp_api_keys WHERE key_hash = $1 AND is_active = TRUE
  4. Returns AccessToken(client_id=key_hash)
  5. ConnectionRegistry.get_connection(key_hash) is called
  6. PortalDatabaseManager.get_user_connection_by_sub(key_hash)
     resolves the Odoo server config (key_hash is NOT hashed again there)

The raw key never appears in logs — only the hash (client_id) is stored
in the auth context and passed through the registry.

Activated when DATABASE_URL is set but OAUTH_ISSUER_URL is not.
"""

import hashlib
import logging
import time
from typing import Dict, Optional, Tuple

import asyncpg
from mcp.server.auth.provider import AccessToken, TokenVerifier

logger = logging.getLogger(__name__)

CACHE_TTL = 60  # seconds — matches ZitadelTokenVerifier


def _hash_key(raw: str) -> str:
    return hashlib.sha256(raw.encode()).hexdigest()


class PortalKeyVerifier(TokenVerifier):
    """Verifies portal-issued MCP API keys against the portal PostgreSQL DB.

    Requires DATABASE_URL pointing to the same PostgreSQL instance as the portal.
    Does NOT need ENCRYPTION_KEY — credential decryption happens later in
    PortalDatabaseManager when the Odoo connection is actually established.
    """

    def __init__(self, database_url: str):
        self._database_url = database_url
        self._pool: Optional[asyncpg.Pool] = None
        self._cache: Dict[str, Tuple[Optional[AccessToken], float]] = {}

    async def _get_pool(self) -> asyncpg.Pool:
        if self._pool is None:
            self._pool = await asyncpg.create_pool(
                self._database_url, min_size=1, max_size=5
            )
        return self._pool

    async def verify_token(self, token: str) -> Optional[AccessToken]:
        """Verify a portal API key. Results cached for CACHE_TTL seconds."""
        key_hash = _hash_key(token)
        cache_key = key_hash[:16]

        cached = self._cache.get(cache_key)
        if cached:
            result, cached_at = cached
            if time.time() - cached_at < CACHE_TTL:
                return result
            del self._cache[cache_key]

        result = await self._verify(key_hash)

        self._cache[cache_key] = (result, time.time())
        if len(self._cache) > 500:
            self._evict_expired()

        return result

    async def _verify(self, key_hash: str) -> Optional[AccessToken]:
        try:
            pool = await self._get_pool()
            row = await pool.fetchrow(
                """
                SELECT k.id
                FROM mcp_api_keys k
                JOIN odoo_servers s ON s.id = k.server_id
                WHERE k.key_hash = $1
                  AND k.is_active = TRUE
                  AND s.is_active = TRUE
                  AND (k.expires_at IS NULL OR k.expires_at > NOW())
                """,
                key_hash,
            )
            if not row:
                logger.debug("Portal key not found or inactive (hash prefix: %s)", key_hash[:8])
                return None

            # Update last_used_at — non-blocking best-effort
            try:
                await pool.execute(
                    "UPDATE mcp_api_keys SET last_used_at = NOW() WHERE key_hash = $1",
                    key_hash,
                )
            except Exception:
                pass  # last_used_at is informational; don't block auth on failure

            # client_id = key_hash (not the raw token) so logs never contain the raw key.
            # PortalDatabaseManager receives this hash and queries key_hash directly.
            return AccessToken(
                token=key_hash,
                client_id=key_hash,
                scopes=[],
                expires_at=None,
            )

        except Exception as e:
            logger.error("Portal key verification failed: %s", e)
            return None

    def _evict_expired(self):
        now = time.time()
        expired = [k for k, (_, ts) in self._cache.items() if now - ts >= CACHE_TTL]
        for k in expired:
            del self._cache[k]
